# Site settings
title: Se-Min Lim
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SeMinLim.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Se-Min Lim
user_description: I'm a researcher in Korea University Research & Business Foundation
user_title: AI & Computer Architecture Researcher
email: jaewoong819@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
