# Site settings
title: Se-Min Lim
description: Se-Min Lim
baseurl: """/particle" # the subpath of your site, e.g. /blog
url: "http://SeMinLim.github.io"

# User settings
username: Se-Min Lim
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: SoC Design & AI Researcher
email: jaewoong819@gmail.com
github_username:  SeMinLim

exclude: ['package.json', 'src' , 'node_modules']
